#!/bin/sh

set -e

## Removes PAM configuration in "/etc/pam.d/common-auth":
pam-auth-update --package --remove rfid


# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p libpam-rfid 
else
	dpkg -L libpam-rfid | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

exit 0
